config/routes.rb
Rails.application.routes.draw do
  resources :hierarchies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hierarchy.rb
# see http://qiita.com/NAKANO_Akihito/items/9cfc87403e5a4e473eb8

class Hierarchy < ApplicationRecord
  belongs_to :parent, class_name: 'Hierarchy', foreign_key: :parent_id
  has_many :children, class_name: 'Hierarchy', foreign_key: :parent_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hierarchies_controller.rb
class HierarchiesController < ApplicationController
  before_action :set_hierarchy, only: [:show, :edit, :update, :destroy]

  # GET /hierarchies
  # GET /hierarchies.json
  def index
    @hierarchies = Hierarchy.where(parent_id: nil)
  end

  # GET /hierarchies/1
  # GET /hierarchies/1.json
  def show
  end

  # GET /hierarchies/new
  def new
    @hierarchy = Hierarchy.new
  end

  # GET /hierarchies/1/edit
  def edit
  end

  # POST /hierarchies
  # POST /hierarchies.json
  def create
    @hierarchy = Hierarchy.new(hierarchy_params)

    respond_to do |format|
      if @hierarchy.save
        format.html { redirect_to @hierarchy, notice: 'Hierarchy was successfully created.' }
        format.json { render :show, status: :created, location: @hierarchy }
      else
        format.html { render :new }
        format.json { render json: @hierarchy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hierarchies/1
  # PATCH/PUT /hierarchies/1.json
  def update
    respond_to do |format|
      if @hierarchy.update(hierarchy_params)
        format.html { redirect_to @hierarchy, notice: 'Hierarchy was successfully updated.' }
        format.json { render :show, status: :ok, location: @hierarchy }
      else
        format.html { render :edit }
        format.json { render json: @hierarchy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hierarchies/1
  # DELETE /hierarchies/1.json
  def destroy
    @hierarchy.destroy
    respond_to do |format|
      format.html { redirect_to hierarchies_url, notice: 'Hierarchy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hierarchy
      @hierarchy = Hierarchy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hierarchy_params
      params.require(:hierarchy).permit(:name, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hierarchies_helper.rb
module HierarchiesHelper
end

app/views/hierarchies/_form.html.erb
<%= form_for(hierarchy) do |f| %>
  <% if hierarchy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hierarchy.errors.count, "error") %> prohibited this hierarchy from being saved:</h2>

      <ul>
      <% hierarchy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :parent_id %>
    <%= f.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hierarchies/_oneline.html.erb
  <tr>
    <td>
    	<% if hierarchy.parent_id.blank? %>
        	<%= hierarchy.name %>
    	<% end %>
	</td>
    <td>
    	<% if hierarchy.parent_id.present? %>
        	<%= hierarchy.name %>
    	<% end %>
	</td>
    <td><%= hierarchy.parent_id %></td>
    <td><%= link_to 'Show', hierarchy %></td>
    <td><%= link_to 'Edit', edit_hierarchy_path(hierarchy) %></td>
    <td><%= link_to 'Destroy', hierarchy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/hierarchies/edit.html.erb
<h1>Editing Hierarchy</h1>

<%= render 'form', hierarchy: @hierarchy %>

<%= link_to 'Show', @hierarchy %> |
<%= link_to 'Back', hierarchies_path %>

app/views/hierarchies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hierarchies</h1>

<table>
  <thead>
    <tr>
      <th>Parent Name</th>
      <th>Child Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hierarchies.each do |hierarchy| %>
   	  <%= render 'oneline', hierarchy: hierarchy %>
      <% hierarchy.children.each do |child| %>
      	<%= render 'oneline', hierarchy: child %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hierarchy', new_hierarchy_path %>

app/views/hierarchies/new.html.erb
<h1>New Hierarchy</h1>

<%= render 'form', hierarchy: @hierarchy %>

<%= link_to 'Back', hierarchies_path %>

app/views/hierarchies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hierarchy.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @hierarchy.parent_id %>
</p>

<%= link_to 'Edit', edit_hierarchy_path(@hierarchy) %> |
<%= link_to 'Back', hierarchies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dbsample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>